version: '3'
services:

  console-api:
    image: console-api:v1
    container_name: console-api
    build:
      context: .
      dockerfile: Dockerfile.api.deploy
    ports:
      - 8585:8585