FROM nginx:1.14.1-alpine

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

## Copy our default nginx config
COPY nginx.conf /etc/nginx/nginx.conf

## From "builder" stage copy over the artifacts in dist folder to default nginx public folder
COPY dist /usr/share/nginx/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]






